#!/bin/bash

testdir=test

make clean
make

echo

for file in op.c cond.c loop.c simp.c func.c struct.c; do
	path="$testdir/$file"
	echo "Running fcc on $path"
	./fcc "$path"
done

echo
sleep .5
echo "Showing diffs..."
sleep .5

for file in op.S cond.S loop.S simp.S func.S struct.S; do
	path="$testdir/old/$file"
	diff -y $path $file | less
done
